export const contacts = [
  {
    id: 1,
    image: require('../../assets/Profile/goku.jpeg'),
    name: 'Son Goku',
    message: 'Hai menzionato Son Goku nella tua storia',
    time: 'ora',
  },
  {
    id: 2,
    image: require('../../assets/Profile/trunks-future.jpeg'),
    name: 'Trunks',
    message: 'Ha messo "Mi piace" a un messaggio',
    time: ' 11.30 pm',
  },
  {
    id: 3,
    image: require('../../assets/Profile/goan.png'),
    name: 'Goan',
    message: 'Ti ha menzionato nella sua storia',
    time: 'Ieri',
  },
  {
    id: 4,
    image: require('../../assets/Profile/Bulma&V.jpeg'),
    name: 'Bulma',
    message: 'Ti ha menzionato nella sua storia',
    time: 'Ieri',
  },
  {
    id: 5,
    image: require('../../assets/Profile/goten.jpeg'),
    name: 'Goten',
    message: 'Ha risposto alla tua storia',
    time: '2 giorni fa',
  },
  {
    id: 6,
    image: require('../../assets/Profile/pan.jpeg'),
    name: 'Pan',
    message: '😂',
    time: ' 1 sett.',
  },
  {
    id: 7,
    image: require('../../assets/Profile/bra.png'),
    name: 'Bra',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 8,
    image: require('../../assets/Profile/c-18.jpeg'),
    name: 'C-18',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 9,
    image: require('../../assets/Profile/broly.png'),
    name: 'Broly',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 10,
    image: require('../../assets/Profile/c-17.png'),
    name: 'C - 17',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 11,
    image: require('../../assets/Profile/freezer.png'),
    name: 'Freezer',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 12,
    image: require('../../assets/Profile/cell.png'),
    name: 'Cell',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 13,
    image: require('../../assets/Profile/black_Goku.png'),
    name: 'Black Goku',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 14,
    image: require('../../assets/Profile/Majin_Buu.png'),
    name: 'Bu',
    message: '',
    time: ' 1 sett.',
  },
  {
    id: 15,
    image: require('../../assets/Profile/Majin-Bu.png'),
    name: 'Majin Bu',
    message: '',
    time: ' 1 sett.',
  },
]
